---

#Simple Ansible Playbook to build and run a Docker containers

- name: Playbook to build and run Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Build a Docker image using webapp.war file
      docker_image:
        name: simple-docker-image
        build:
          path: /home/edureka/project/edurekalab
          pull: false
        source: build
    - name: Tag and Push image to registry 
      docker_image:
         name: simple-docker-image
         repository: devadharpraveenedureka/devadharpraveenedureka
         tag: latest
         push: true
    - name: Run Docker container using simple-docker-image
      docker_container:
        name: simple-docker-container
        image: devadharpraveenedureka/devadharpraveenedureka:latest
        state: started
        recreate: yes
        detach: true
        ports:
          - "8888:8080"
